// ============================================================
// functions/_middleware.js
// Cloudflare Pages Middleware
//
// কাজ: Browser যখন /assets/js/config.js চাইবে, তখন
//       static file এর বদলে Cloudflare env variable থেকে
//       পড়ে dynamically CONFIG তৈরি করে দেবে।
//
// ফলে: assets/js/config.js এ কোনো credentials থাকবে না।
//       সব কিছু Cloudflare Dashboard → Environment Variables এ।
// ============================================================

export async function onRequest(context) {
    const url = new URL(context.request.url);

    // শুধু /assets/js/config.js এর জন্য কাজ করবে
    if (url.pathname === '/assets/js/config.js') {
        const env = context.env;

        // Single quotes escape করা (security)
        const s = (v) => (v || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");

        const configJs = `// ============================================================
// Auto-generated by Cloudflare Pages Middleware
// সরাসরি edit করবেন না — Cloudflare Dashboard → Environment Variables এ বদলান
// ============================================================

var CONFIG = {

    // ── DB Provider ──────────────────────────────────────────
    // Cloudflare Env: DB_PROVIDER = 'supabase' | 'appwrite'
    DB_PROVIDER: '${s(env.DB_PROVIDER) || 'supabase'}',

    // ── Supabase ─────────────────────────────────────────────
    SUPABASE_URL:      '${s(env.SUPABASE_URL)}',
    SUPABASE_ANON_KEY: '${s(env.SUPABASE_ANON_KEY)}',

    // ── Appwrite ─────────────────────────────────────────────
    APPWRITE_ENDPOINT:    '${s(env.APPWRITE_ENDPOINT)}',
    APPWRITE_PROJECT:     '${s(env.APPWRITE_PROJECT)}',
    APPWRITE_DATABASE_ID: '${s(env.APPWRITE_DATABASE_ID)}',

    // ── Frontend Constants (DB ছাড়াই কাজ করে) ───────────────
    CART_KEY:         'fbr_cart',
    DIRECT_ORDER_KEY: 'fbr_direct_order',
    SESSION_KEY:      'fbr_session',
    ADMIN_PATH:       '/admin',

};
`;

        return new Response(configJs, {
            status: 200,
            headers: {
                'Content-Type':  'application/javascript; charset=utf-8',
                'Cache-Control': 'no-store, no-cache', // সবসময় fresh, env বদলালে সাথেসাথে কাজ করবে
            },
        });
    }

    // অন্য সব request স্বাভাবিকভাবে চলবে
    return context.next();
}
